import {
  CompanyType,
  JobDepartment,
  JobLevel,
  JourneyModule,
  OnboardingJourneyTemplate,
  IntelligentOnboardingJourney
} from '../types';

/**
 * Intelligent Onboarding Service
 * Generates personalized onboarding journeys based on company, department, and work level
 */

// ========================================
// Journey Templates by Scenario
// ========================================

const JOURNEY_TEMPLATES: Record<
  CompanyType,
  Record<JobDepartment, Record<JobLevel, OnboardingJourneyTemplate>>
> = {
  MY: {
    Engineering: {
      Junior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Employment Act Awareness',
            description: 'Introduction to Malaysia Employment Act 1955 requirements and obligations',
            isRequired: true,
            estimatedMinutes: 15,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Email & Collaboration Tools',
            description: 'Setup corporate email, Microsoft 365, and Slack accounts',
            isRequired: true,
            estimatedMinutes: 45,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Laptop & Equipment',
            description: 'Provision laptop, monitor, and necessary peripherals based on role requirements',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['doc_1', 'doc_2'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Engineering Fundamentals',
            description: 'Company engineering standards, coding practices, and code review processes',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Engineering Culture Introduction',
            description: 'Meet engineering leads, team structure, and agile workflows',
            isRequired: false,
            estimatedMinutes: 30,
            dependencies: ['it_1'],
          },
        ],
        totalEstimatedMinutes: 300,
      },
      Mid: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Employment Act Awareness',
            description: 'Introduction to Malaysia Employment Act 1955 requirements and obligations',
            isRequired: true,
            estimatedMinutes: 15,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Advanced Development Environment',
            description: 'Setup corporate email, Microsoft 365, Slack, and access to development tools',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Laptop & Equipment',
            description: 'Provision high-performance laptop, dual monitors, and engineering peripherals',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['doc_1', 'doc_2'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Engineering Best Practices',
            description: 'Advanced engineering methodologies, code review standards, and architecture guidelines',
            isRequired: true,
            estimatedMinutes: 180,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Cloud & DevOps Training',
            description: 'AWS, Docker, Kubernetes, and CI/CD pipeline setup and management',
            isRequired: true,
            estimatedMinutes: 150,
            dependencies: ['it_1'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Performance Bonus Structure',
            description: 'Understanding quarterly performance bonuses and KPI-based incentives',
            isRequired: false,
            estimatedMinutes: 30,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Engineering Leadership & Collaboration',
            description: 'Meet senior engineers, technical leads, and cross-functional teams',
            isRequired: false,
            estimatedMinutes: 45,
            dependencies: ['it_1'],
          },
        ],
        totalEstimatedMinutes: 590,
      },
      Senior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Employment Act Compliance',
            description: 'Advanced knowledge of Malaysia Employment Act 1955 for team management',
            isRequired: true,
            estimatedMinutes: 20,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Senior Development Environment',
            description: 'Setup corporate email, Microsoft 365, Slack, Jira, and administrative access',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Premium Equipment Package',
            description: 'Provision MacBook Pro, dual 4K monitors, mechanical keyboard, and accessories',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['doc_1', 'doc_2'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Technical Leadership',
            description: 'Advanced technical leadership, architecture decisions, and team mentoring',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'DevOps & Infrastructure',
            description: 'Infrastructure management, deployment strategies, and system architecture',
            isRequired: true,
            estimatedMinutes: 180,
            dependencies: ['it_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'System Access',
            description: 'Grant access to production databases, CI/CD pipelines, and monitoring systems',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Executive Compensation Package',
            description: 'Detailed breakdown of salary, bonuses, stock options, and benefits',
            isRequired: false,
            estimatedMinutes: 45,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Engineering Culture Integration',
            description: 'Lead engineering culture initiatives, innovation workshops, and knowledge sharing',
            isRequired: false,
            estimatedMinutes: 60,
          },
        ],
        totalEstimatedMinutes: 745,
      },
      Executive: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Strategic Compliance Leadership',
            description: 'Understanding employment laws at executive level for strategic decision-making',
            isRequired: true,
            estimatedMinutes: 30,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Executive Technology Suite',
            description: 'Setup corporate email, Microsoft 365, Slack, and executive dashboards',
            isRequired: true,
            estimatedMinutes: 45,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Executive Devices',
            description: 'Provision high-end laptop, premium peripherals, and mobile devices',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['doc_1', 'doc_2'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Executive Leadership Development',
            description: 'Advanced leadership programs, strategic thinking, and decision-making frameworks',
            isRequired: true,
            estimatedMinutes: 300,
            dependencies: ['it_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'Executive Access Rights',
            description: 'Grant access to financial systems, strategic reports, and board-level dashboards',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_1'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Executive Benefits Overview',
            description: 'Comprehensive benefits package including health, life insurance, and retirement planning',
            isRequired: false,
            estimatedMinutes: 60,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Leadership & Culture',
            description: 'Define and promote organizational culture, values, and employee engagement strategies',
            isRequired: false,
            estimatedMinutes: 90,
          },
        ],
        totalEstimatedMinutes: 645,
      },
    },
    Sales: {
      Junior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Employment Act Basics',
            description: 'Overview of Malaysia Employment Act 1955 for sales roles',
            isRequired: true,
            estimatedMinutes: 15,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Sales Tools Setup',
            description: 'Setup CRM software (Salesforce/HubSpot), email marketing tools, and LinkedIn Sales Navigator',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Mobile & Communication Devices',
            description: 'Provision company mobile, sales headset, and portable devices for client meetings',
            isRequired: true,
            estimatedMinutes: 45,
            dependencies: ['doc_1', 'doc_2'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Sales Fundamentals',
            description: 'Company sales processes, CRM training, and customer relationship management',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Product & Market Knowledge',
            description: 'Product catalog training, competitive analysis, and market positioning strategies',
            isRequired: true,
            estimatedMinutes: 150,
            dependencies: ['it_1'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Sales Commission Structure',
            description: 'Understanding commission tiers, bonus structures, and sales incentives',
            isRequired: false,
            estimatedMinutes: 30,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Sales Team Culture',
            description: 'Introduction to sales team culture, customer-first mindset, and collaboration practices',
            isRequired: false,
            estimatedMinutes: 45,
            dependencies: ['it_1'],
          },
        ],
        totalEstimatedMinutes: 525,
      },
      Mid: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Sales Compliance Regulations',
            description: 'Understanding employment laws for sales roles and commission-based compensation',
            isRequired: true,
            estimatedMinutes: 20,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Advanced Sales Tech Stack',
            description: 'Configure CRM integrations, marketing automation tools, and analytics dashboards',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Premium Sales Equipment',
            description: 'Provision high-performance laptop, dual monitors, and sales presentation tools',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['doc_1', 'doc_2'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Advanced Sales Techniques',
            description: 'Consultative selling, negotiation strategies, and key account management',
            isRequired: true,
            estimatedMinutes: 180,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Market Analysis & Strategy',
            description: 'Market research, competitive analysis, and strategic sales planning',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['it_1'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Sales Performance Incentives',
            description: 'Commission structures, quotas, and achievement bonuses',
            isRequired: false,
            estimatedMinutes: 45,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Sales Leadership & Mentoring',
            description: 'Lead sales team culture initiatives and junior sales representative mentoring',
            isRequired: false,
            estimatedMinutes: 60,
          },
        ],
        totalEstimatedMinutes: 735,
      },
      Senior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Strategic Sales Compliance',
            description: 'Advanced knowledge of employment laws for sales leadership and commission structures',
            isRequired: true,
            estimatedMinutes: 30,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Sales Leadership Tech Suite',
            description: 'Setup CRM administration, marketing automation, and sales analytics platforms',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Executive Sales Devices',
            description: 'Provision premium laptop, presentation tools, and communication devices',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['doc_1', 'doc_2'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Sales Leadership Development',
            description: 'Advanced sales leadership, team management, and strategic account development',
            isRequired: true,
            estimatedMinutes: 300,
            dependencies: ['it_1'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Market & Competitive Intelligence',
            description: 'Market research, competitor analysis, and strategic market positioning',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['it_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'Sales System Access',
            description: 'Grant access to CRM databases, sales reports, and commission tracking systems',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Sales Executive Benefits',
            description: 'Executive benefits including health coverage, performance bonuses, and retirement planning',
            isRequired: false,
            estimatedMinutes: 60,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Sales Culture Leadership',
            description: 'Define sales team culture, lead sales culture initiatives, and customer satisfaction programs',
            isRequired: false,
            estimatedMinutes: 90,
          },
        ],
        totalEstimatedMinutes: 890,
      },
    },
    HR: {
      Junior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'HR Compliance Fundamentals',
            description: 'Introduction to HR compliance, employment laws, and regulatory requirements',
            isRequired: true,
            estimatedMinutes: 30,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'HRIS Systems',
            description: 'Setup HR Information Systems, employee database access, and reporting tools',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'HR Tools & Software',
            description: 'Configure HR software, time and attendance systems, and leave management platforms',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'HR Fundamentals',
            description: 'Core HR functions: recruitment, onboarding, payroll, and employee relations',
            isRequired: true,
            estimatedMinutes: 180,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Employment Law & Compliance',
            description: 'In-depth training on Malaysia Employment Act 1955, industrial relations, and dispute resolution',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['comp_1'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'HR Benefits Overview',
            description: 'Understanding company benefits, HR policies, and employee welfare programs',
            isRequired: false,
            estimatedMinutes: 45,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'HR Team Culture',
            description: 'Introduction to HR team culture, company values, and employee engagement strategies',
            isRequired: false,
            estimatedMinutes: 45,
            dependencies: ['it_1'],
          },
        ],
        totalEstimatedMinutes: 690,
      },
      Mid: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Advanced HR Compliance',
            description: 'Comprehensive knowledge of employment laws for HR operations and advisory',
            isRequired: true,
            estimatedMinutes: 45,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Advanced HRIS Setup',
            description: 'Configure HRIS integrations, payroll system access, and analytics dashboards',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'HR Administration Tools',
            description: 'Setup advanced HR tools, document management systems, and employee self-service portals',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'HR Operations & Strategy',
            description: 'Strategic HR planning, workforce analytics, and organizational development',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Advanced Compliance & Industrial Relations',
            description: 'Advanced employment law, collective bargaining, and industrial relations management',
            isRequired: true,
            estimatedMinutes: 300,
            dependencies: ['comp_1'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Compensation & Benefits Strategy',
            description: 'Understanding compensation structures, benefits administration, and total rewards strategy',
            isRequired: false,
            estimatedMinutes: 60,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'HR Leadership & Organizational Culture',
            description: 'Lead HR initiatives, culture programs, and organizational development strategies',
            isRequired: false,
            estimatedMinutes: 90,
          },
        ],
        totalEstimatedMinutes: 1005,
      },
      Senior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Strategic HR Leadership',
            description: 'Executive-level knowledge of employment laws and strategic HR decision-making',
            isRequired: true,
            estimatedMinutes: 60,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Executive HRIS Management',
            description: 'Oversee HRIS systems, payroll platforms, and HR technology strategy',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'HR Systems Administration',
            description: 'Manage HR software integrations, system access, and technology governance',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Executive HR Leadership',
            description: 'Advanced HR leadership, organizational design, and change management',
            isRequired: true,
            estimatedMinutes: 360,
            dependencies: ['it_1'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Strategic Workforce Planning',
            description: 'Workforce analytics, succession planning, and talent strategy development',
            isRequired: true,
            estimatedMinutes: 300,
            dependencies: ['comp_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'Executive HR Access',
            description: 'Full access to HR systems, payroll data, and strategic reports',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Executive Benefits Administration',
            description: 'Executive-level benefits oversight, compensation strategy, and total rewards management',
            isRequired: false,
            estimatedMinutes: 75,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Organizational Culture & Values',
            description: 'Define company culture, values, and lead organizational culture initiatives',
            isRequired: false,
            estimatedMinutes: 120,
          },
        ],
        totalEstimatedMinutes: 1170,
      },
    },
    Finance: {
      Junior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Finance Compliance Overview',
            description: 'Introduction to financial regulations and compliance requirements',
            isRequired: true,
            estimatedMinutes: 20,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Financial Systems Setup',
            description: 'Setup accounting software (QuickBooks/Xero), expense management, and financial reporting tools',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Finance Tools & Calculators',
            description: 'Configure financial modeling tools, tax calculators, and payroll systems',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Finance Fundamentals',
            description: 'Core finance functions: accounting, financial reporting, and basic financial management',
            isRequired: true,
            estimatedMinutes: 180,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Financial Analysis & Reporting',
            description: 'Advanced financial analysis, reporting standards, and financial modeling',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['it_1'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Finance Team Benefits',
            description: 'Understanding finance team benefits including professional certifications and study support',
            isRequired: false,
            estimatedMinutes: 30,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Finance Team Culture',
            description: 'Introduction to finance team culture, accuracy focus, and collaboration with other departments',
            isRequired: false,
            estimatedMinutes: 45,
            dependencies: ['it_1'],
          },
        ],
        totalEstimatedMinutes: 725,
      },
      Mid: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Advanced Finance Compliance',
            description: 'Comprehensive knowledge of financial regulations and tax compliance',
            isRequired: true,
            estimatedMinutes: 45,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Financial Systems Integration',
            description: 'Integrate accounting software, payroll systems, and financial reporting platforms',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Advanced Finance Tools',
            description: 'Configure financial modeling, budget management, and forecasting tools',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Financial Management & Strategy',
            description: 'Financial planning, budgeting, and strategic financial management',
            isRequired: true,
            estimatedMinutes: 300,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Advanced Financial Analysis',
            description: 'Advanced financial analysis, audit preparation, and strategic financial reporting',
            isRequired: true,
            estimatedMinutes: 360,
            dependencies: ['comp_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'Financial System Access',
            description: 'Grant access to financial systems, budget databases, and strategic reports',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Compensation Strategy Overview',
            description: 'Understanding compensation structures, benefits strategy, and financial planning',
            isRequired: false,
            estimatedMinutes: 60,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Finance Leadership & Collaboration',
            description: 'Lead finance team initiatives, cross-department collaboration, and financial accuracy culture',
            isRequired: false,
            estimatedMinutes: 90,
          },
        ],
        totalEstimatedMinutes: 1145,
      },
      Senior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Executive Finance Compliance',
            description: 'Executive-level knowledge of financial regulations and strategic financial compliance',
            isRequired: true,
            estimatedMinutes: 60,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Executive Financial Systems',
            description: 'Oversee financial systems, implement financial technology strategy, and manage financial governance',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Finance Systems Administration',
            description: 'Manage financial software integrations, system access, and financial technology oversight',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Executive Finance Leadership',
            description: 'Advanced financial leadership, strategic financial planning, and treasury management',
            isRequired: true,
            estimatedMinutes: 480,
            dependencies: ['it_1'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Strategic Financial Management',
            description: 'Strategic financial planning, investment decisions, and financial risk management',
            isRequired: true,
            estimatedMinutes: 360,
            dependencies: ['comp_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'Executive Financial Access',
            description: 'Full access to all financial systems, strategic reports, and board-level financial dashboards',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Executive Benefits Administration',
            description: 'Executive-level benefits oversight, compensation strategy, and financial benefits management',
            isRequired: false,
            estimatedMinutes: 90,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Financial Stewardship & Culture',
            description: 'Define financial stewardship culture, risk management values, and ethical financial practices',
            isRequired: false,
            estimatedMinutes: 120,
          },
        ],
        totalEstimatedMinutes: 1395,
      },
    },
    Operations: {
      Junior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Operations Compliance Basics',
            description: 'Introduction to operations compliance and workplace safety regulations',
            isRequired: true,
            estimatedMinutes: 15,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Operations Tools Setup',
            description: 'Setup project management tools, inventory systems, and operations dashboards',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Operational Equipment',
            description: 'Provide operational equipment, tools, and supplies as needed',
            isRequired: true,
            estimatedMinutes: 45,
            dependencies: ['doc_1', 'doc_2'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Operations Fundamentals',
            description: 'Core operations processes, standard operating procedures, and quality management',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Process Improvement',
            description: 'Process optimization, continuous improvement methodologies, and operational excellence',
            isRequired: true,
            estimatedMinutes: 180,
            dependencies: ['it_1'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Operations Team Benefits',
            description: 'Understanding operations team benefits and workplace safety programs',
            isRequired: false,
            estimatedMinutes: 30,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Operations Culture',
            description: 'Introduction to operations culture, efficiency focus, and continuous improvement mindset',
            isRequired: false,
            estimatedMinutes: 45,
            dependencies: ['it_1'],
          },
        ],
        totalEstimatedMinutes: 515,
      },
      Mid: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Operations Compliance',
            description: 'Comprehensive knowledge of operations regulations and workplace safety standards',
            isRequired: true,
            estimatedMinutes: 30,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Operations Management Systems',
            description: 'Configure ERP systems, inventory management, and operations analytics platforms',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Advanced Operations Tools',
            description: 'Setup project management (Asana/Jira), supply chain tools, and operational dashboards',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Operations Management',
            description: 'Operations planning, resource allocation, and performance management',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Process Optimization',
            description: 'Advanced process optimization, lean methodologies, and operational excellence',
            isRequired: true,
            estimatedMinutes: 300,
            dependencies: ['comp_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'Operations System Access',
            description: 'Grant access to operations systems, inventory databases, and performance reports',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Operational Excellence Rewards',
            description: 'Understanding operational excellence programs and performance-based incentives',
            isRequired: false,
            estimatedMinutes: 45,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Operational Excellence Culture',
            description: 'Lead operations culture initiatives, continuous improvement programs, and efficiency focus',
            isRequired: false,
            estimatedMinutes: 90,
          },
        ],
        totalEstimatedMinutes: 965,
      },
      Senior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Strategic Operations Compliance',
            description: 'Executive-level knowledge of operations regulations and strategic compliance planning',
            isRequired: true,
            estimatedMinutes: 45,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'EPF Registration',
            description: 'Register with Employees Provident Fund (KWSP) - mandatory for Malaysian employees',
            isRequired: true,
            estimatedMinutes: 30,
            requiresUpload: true,
          },
          {
            id: 'doc_2',
            type: 'documentation',
            title: 'NRIC Verification',
            description: 'Verify NRIC for statutory compliance and payroll setup',
            isRequired: true,
            estimatedMinutes: 20,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Executive Operations Systems',
            description: 'Oversee operations technology infrastructure, ERP systems, and operational strategy',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Operations Governance',
            description: 'Manage operations technology governance, system access, and operational technology strategy',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Executive Operations Leadership',
            description: 'Advanced operations leadership, strategic planning, and organizational design',
            isRequired: true,
            estimatedMinutes: 360,
            dependencies: ['it_1'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Strategic Operations Management',
            description: 'Strategic operations planning, supply chain management, and business continuity',
            isRequired: true,
            estimatedMinutes: 300,
            dependencies: ['comp_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'Executive Operations Access',
            description: 'Full access to operations systems, strategic reports, and executive operations dashboards',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Operational Strategy Rewards',
            description: 'Executive-level benefits for operational excellence and strategic contributions',
            isRequired: false,
            estimatedMinutes: 75,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Operational Excellence Culture',
            description: 'Define operational excellence culture, safety values, and continuous improvement mindset',
            isRequired: false,
            estimatedMinutes: 120,
          },
        ],
        totalEstimatedMinutes: 1230,
      },
    },
    IT: {
      Junior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'IT Compliance Basics',
            description: 'Introduction to IT compliance, data security, and software licensing',
            isRequired: true,
            estimatedMinutes: 20,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Basic Development Environment',
            description: 'Setup developer laptop, IDE, version control, and basic development tools',
            isRequired: true,
            estimatedMinutes: 60,
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Development Tools',
            description: 'Setup code repositories, development platforms, and collaboration tools',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Development Fundamentals',
            description: 'Company coding standards, development practices, and code review processes',
            isRequired: true,
            estimatedMinutes: 180,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Advanced Development Practices',
            description: 'Advanced development methodologies, testing frameworks, and deployment strategies',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['it_1'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'IT Team Benefits',
            description: 'Understanding IT team benefits including equipment upgrades and professional development budget',
            isRequired: false,
            estimatedMinutes: 30,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Developer Culture',
            description: 'Introduction to developer culture, agile practices, and innovation mindset',
            isRequired: false,
            estimatedMinutes: 45,
            dependencies: ['it_1'],
          },
        ],
        totalEstimatedMinutes: 665,
      },
      Mid: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'IT Security & Compliance',
            description: 'Advanced knowledge of IT security, data protection, and software compliance',
            isRequired: true,
            estimatedMinutes: 30,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Advanced Development Environment',
            description: 'Setup high-performance development workstation, multiple monitors, and advanced development tools',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'DevOps & Infrastructure',
            description: 'Configure CI/CD pipelines, testing environments, and deployment infrastructure',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Software Architecture',
            description: 'System design, microservices architecture, and scalability planning',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Advanced DevOps Practices',
            description: 'Container orchestration, infrastructure as code, and advanced deployment strategies',
            isRequired: true,
            estimatedMinutes: 300,
            dependencies: ['it_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'System Access',
            description: 'Grant access to development servers, testing environments, and production systems',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'IT Professional Development',
            description: 'Professional certifications, conference attendance, and advanced training budget',
            isRequired: false,
            estimatedMinutes: 60,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Engineering Culture Integration',
            description: 'Collaborate with engineering teams, share technical knowledge, and contribute to engineering culture',
            isRequired: false,
            estimatedMinutes: 60,
          },
        ],
        totalEstimatedMinutes: 934,
      },
      Senior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Enterprise IT Compliance',
            description: 'Executive-level IT compliance, enterprise security, and technology governance',
            isRequired: true,
            estimatedMinutes: 45,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Enterprise Architecture',
            description: 'Design and oversee enterprise architecture, technology strategy, and system integration',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Infrastructure Leadership',
            description: 'Lead infrastructure management, cloud strategy, and technology governance',
            isRequired: true,
            estimatedMinutes: 180,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Technology Leadership',
            description: 'Advanced technology leadership, digital transformation, and innovation management',
            isRequired: true,
            estimatedMinutes: 360,
            dependencies: ['it_1'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Enterprise Architecture & Strategy',
            description: 'Enterprise architecture planning, technology roadmap, and digital transformation strategy',
            isRequired: true,
            estimatedMinutes: 480,
            dependencies: ['comp_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'Executive IT Access',
            description: 'Full access to all IT systems, infrastructure, and technology strategy documents',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Executive Technology Benefits',
            description: 'Executive-level technology benefits including equity options and innovation budget',
            isRequired: false,
            estimatedMinutes: 90,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Technology Leadership & Culture',
            description: 'Lead technology culture initiatives, innovation programs, and digital transformation mindset',
            isRequired: false,
            estimatedMinutes: 120,
          },
        ],
        totalEstimatedMinutes: 1485,
      },
    },
    Customer Support: {
      Junior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Customer Service Compliance',
            description: 'Introduction to customer service standards and data protection regulations',
            isRequired: true,
            estimatedMinutes: 15,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Customer Support Tools',
            description: 'Setup helpdesk software (Zendesk/Freshdesk), CRM access, and customer database',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['comp_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Customer Service Fundamentals',
            description: 'Core customer service skills, communication techniques, and issue resolution',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['it_1'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Product Knowledge',
            description: 'Product knowledge, company policies, and service standards training',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['it_1'],
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Customer-Centric Culture',
            description: 'Introduction to customer-first culture, service excellence mindset, and problem-solving focus',
            isRequired: false,
            estimatedMinutes: 30,
            dependencies: ['it_1'],
          },
        ],
        totalEstimatedMinutes: 315,
      },
      Mid: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Advanced Customer Compliance',
            description: 'Comprehensive knowledge of customer service regulations and privacy standards',
            isRequired: true,
            estimatedMinutes: 30,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Advanced Support Systems',
            description: 'Configure helpdesk systems, knowledge bases, and customer communication platforms',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'CRM & Customer Database',
            description: 'Setup CRM integrations, customer data management, and analytics dashboards',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Advanced Customer Service',
            description: 'Advanced customer service techniques, conflict resolution, and customer relationship management',
            isRequired: true,
            estimatedMinutes: 180,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Quality Management',
            description: 'Service quality standards, customer feedback management, and continuous improvement',
            isRequired: true,
            estimatedMinutes: 150,
            dependencies: ['comp_1'],
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Service Excellence Culture',
            description: 'Lead service excellence initiatives, customer satisfaction programs, and quality culture',
            isRequired: false,
            estimatedMinutes: 60,
          },
        ],
        totalEstimatedMinutes: 690,
      },
      Senior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Strategic Customer Compliance',
            description: 'Executive-level knowledge of customer service regulations and strategic compliance',
            isRequired: true,
            estimatedMinutes: 45,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Enterprise Support Systems',
            description: 'Oversee customer support technology, CRM strategy, and customer experience platforms',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Customer Experience Platforms',
            description: 'Manage customer experience platforms, omnichannel support, and service automation',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Customer Experience Leadership',
            description: 'Advanced customer experience management, service strategy, and customer journey optimization',
            isRequired: true,
            estimatedMinutes: 360,
            dependencies: ['it_1'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Strategic Customer Relations',
            description: 'Strategic customer relationship management, loyalty programs, and customer lifetime value',
            isRequired: true,
            estimatedMinutes: 300,
            dependencies: ['comp_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'Executive Customer Access',
            description: 'Full access to customer systems, strategic reports, and customer insights',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'benefits_1',
            type: 'benefits',
            title: 'Service Excellence Rewards',
            description: 'Executive-level rewards for service excellence, customer satisfaction, and team performance',
            isRequired: false,
            estimatedMinutes: 75,
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Customer-Centric Culture Leadership',
            description: 'Lead customer-centric culture initiatives, service excellence values, and customer satisfaction focus',
            isRequired: false,
            estimatedMinutes: 120,
          },
        ],
        totalEstimatedMinutes: 1170,
      },
    },
  },
  SG: {
    Engineering: {
      Junior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Employment Act Awareness',
            description: 'Introduction to Singapore Employment Act and employment practices',
            isRequired: true,
            estimatedMinutes: 15,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'Work Pass Application',
            description: 'Apply for Employment Pass for non-Singaporean employees',
            isRequired: true,
            estimatedMinutes: 60,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Basic Development Environment',
            description: 'Setup developer laptop, IDE, version control, and basic development tools',
            isRequired: true,
            estimatedMinutes: 60,
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Development Tools',
            description: 'Setup code repositories, development platforms, and collaboration tools',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Engineering Fundamentals',
            description: 'Company engineering standards, coding practices, and code review processes',
            isRequired: true,
            estimatedMinutes: 180,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Advanced Development Practices',
            description: 'Advanced development methodologies, testing frameworks, and deployment strategies',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['it_1'],
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Engineering Culture Introduction',
            description: 'Meet engineering leads, team structure, and agile workflows',
            isRequired: false,
            estimatedMinutes: 30,
            dependencies: ['it_1'],
          },
        ],
        totalEstimatedMinutes: 685,
      },
      Mid: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Employment Act Compliance',
            description: 'Comprehensive knowledge of Singapore Employment Act for engineering roles',
            isRequired: true,
            estimatedMinutes: 20,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'Work Pass Application',
            description: 'Apply for Employment Pass for non-Singaporean employees',
            isRequired: true,
            estimatedMinutes: 60,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Advanced Development Environment',
            description: 'Setup high-performance development workstation, multiple monitors, and advanced development tools',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'DevOps & Infrastructure',
            description: 'Configure CI/CD pipelines, testing environments, and deployment infrastructure',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Software Architecture',
            description: 'System design, microservices architecture, and scalability planning',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Advanced DevOps Practices',
            description: 'Container orchestration, infrastructure as code, and advanced deployment strategies',
            isRequired: true,
            estimatedMinutes: 300,
            dependencies: ['it_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'System Access',
            description: 'Grant access to development servers, testing environments, and production systems',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Engineering Culture Integration',
            description: 'Collaborate with engineering teams, share technical knowledge, and contribute to engineering culture',
            isRequired: false,
            estimatedMinutes: 60,
          },
        ],
        totalEstimatedMinutes: 934,
      },
      Senior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Strategic Employment Act Compliance',
            description: 'Executive-level knowledge of Singapore Employment Act for strategic decisions',
            isRequired: true,
            estimatedMinutes: 30,
          },
          {
            id: 'doc_1',
            type: 'documentation',
            title: 'Work Pass Application',
            description: 'Apply for Employment Pass for non-Singaporean employees',
            isRequired: true,
            estimatedMinutes: 60,
            requiresUpload: true,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Enterprise Architecture',
            description: 'Design and oversee enterprise architecture, technology strategy, and system integration',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Infrastructure Leadership',
            description: 'Lead infrastructure management, cloud strategy, and technology governance',
            isRequired: true,
            estimatedMinutes: 180,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Technology Leadership',
            description: 'Advanced technology leadership, digital transformation, and innovation management',
            isRequired: true,
            estimatedMinutes: 360,
            dependencies: ['it_1'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Enterprise Architecture & Strategy',
            description: 'Enterprise architecture planning, technology roadmap, and digital transformation strategy',
            isRequired: true,
            estimatedMinutes: 480,
            dependencies: ['comp_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'Executive IT Access',
            description: 'Full access to all IT systems, infrastructure, and technology strategy documents',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Technology Leadership & Culture',
            description: 'Lead technology culture initiatives, innovation programs, and digital transformation mindset',
            isRequired: false,
            estimatedMinutes: 120,
          },
        ],
        totalEstimatedMinutes: 1440,
      },
    },
    Sales: {
      Junior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Employment Act Basics',
            description: 'Overview of Singapore Employment Act for sales roles',
            isRequired: true,
            estimatedMinutes: 15,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Sales Tools Setup',
            description: 'Setup CRM software (Salesforce/HubSpot), email marketing tools, and LinkedIn Sales Navigator',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Mobile & Communication Devices',
            description: 'Provision company mobile, sales headset, and portable devices for client meetings',
            isRequired: true,
            estimatedMinutes: 45,
            dependencies: ['comp_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Sales Fundamentals',
            description: 'Company sales processes, CRM training, and customer relationship management',
            isRequired: true,
            estimatedMinutes: 120,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Product & Market Knowledge',
            description: 'Product catalog training, competitive analysis, and market positioning strategies',
            isRequired: true,
            estimatedMinutes: 150,
            dependencies: ['it_1'],
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Sales Team Culture',
            description: 'Introduction to sales team culture, customer-first mindset, and collaboration practices',
            isRequired: false,
            estimatedMinutes: 45,
            dependencies: ['it_1'],
          },
        ],
        totalEstimatedMinutes: 435,
      },
      Mid: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Sales Compliance Regulations',
            description: 'Understanding employment laws for sales roles and commission-based compensation',
            isRequired: true,
            estimatedMinutes: 20,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Advanced Sales Tech Stack',
            description: 'Configure CRM integrations, marketing automation tools, and analytics dashboards',
            isRequired: true,
            estimatedMinutes: 90,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Premium Sales Equipment',
            description: 'Provision high-performance laptop, dual monitors, and sales presentation tools',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Advanced Sales Techniques',
            description: 'Consultative selling, negotiation strategies, and key account management',
            isRequired: true,
            estimatedMinutes: 180,
            dependencies: ['it_1', 'it_2'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Market Analysis & Strategy',
            description: 'Market research, competitive analysis, and strategic sales planning',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['it_1'],
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Sales Leadership & Mentoring',
            description: 'Lead sales team culture initiatives and junior sales representative mentoring',
            isRequired: false,
            estimatedMinutes: 60,
          },
        ],
        totalEstimatedMinutes: 690,
      },
      Senior: {
        modules: [
          {
            id: 'comp_1',
            type: 'compliance',
            title: 'Strategic Sales Compliance',
            description: 'Advanced knowledge of employment laws for sales leadership and commission structures',
            isRequired: true,
            estimatedMinutes: 30,
          },
          {
            id: 'it_1',
            type: 'it_setup',
            title: 'Sales Leadership Tech Suite',
            description: 'Setup CRM administration, marketing automation, and sales analytics platforms',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['comp_1'],
          },
          {
            id: 'it_2',
            type: 'it_setup',
            title: 'Executive Sales Devices',
            description: 'Provision premium laptop, presentation tools, and communication devices',
            isRequired: true,
            estimatedMinutes: 60,
            dependencies: ['it_1'],
          },
          {
            id: 'training_1',
            type: 'training',
            title: 'Sales Leadership Development',
            description: 'Advanced sales leadership, team management, and strategic account development',
            isRequired: true,
            estimatedMinutes: 300,
            dependencies: ['it_1'],
          },
          {
            id: 'training_2',
            type: 'training',
            title: 'Market & Competitive Intelligence',
            description: 'Market research, competitor analysis, and strategic market positioning',
            isRequired: true,
            estimatedMinutes: 240,
            dependencies: ['it_1'],
          },
          {
            id: 'access_1',
            type: 'access',
            title: 'Sales System Access',
            description: 'Grant access to CRM databases, sales reports, and commission tracking systems',
            isRequired: true,
            estimatedMinutes: 30,
            dependencies: ['training_2'],
          },
          {
            id: 'culture_1',
            type: 'culture',
            title: 'Sales Culture Leadership',
            description: 'Define sales team culture, lead sales culture initiatives, and customer satisfaction programs',
            isRequired: false,
            estimatedMinutes: 90,
          },
        ],
        totalEstimatedMinutes: 840,
      },
    },
  },
};

/**
 * Generate an intelligent onboarding journey based on company, department, and level
 */
export const generateIntelligentOnboardingJourney = (
  company: CompanyType,
  department: JobDepartment,
  level: JobLevel,
  customizations?: Record<string, any>,
): IntelligentOnboardingJourney => {
  // Get the appropriate template
  const template = JOURNEY_TEMPLATES[company]?.[department]?.[level];

  if (!template) {
    throw new Error(
      `No journey template found for ${company} - ${department} - ${level}`
    );
  }

  // Start with the base template
  let journey = {
    templateId: `${company}_${department}_${level}`,
    employeeName: '[EMPLOYEE_NAME]',
    email: '[EMPLOYEE_EMAIL]',
    position: '[POSITION]',
    department,
    level,
    company,
    generatedAt: new Date().toISOString(),
    status: 'generated',
    customizations: customizations || {},
  };

  // Apply customizations if provided
  if (customizations) {
    journey.modules = template.modules.map((module) => ({
      ...module,
      ...(customizations[module.id] || {}),
    }));
  }

  return journey;
};

/**
 * Get all available journey templates
 */
export const getAvailableJourneyTemplates = (): OnboardingJourneyTemplate[] => {
  const templates: OnboardingJourneyTemplate[] = [];

  for (const company of ['MY', 'SG'] as CompanyType[]) {
    for (const department of Object.keys(
      JOURNEY_TEMPLATES[company] || {}
    ) as JobDepartment[]) {
      for (const level of ['Junior', 'Mid', 'Senior'] as JobLevel[]) {
        const template = JOURNEY_TEMPLATES[company]?.[department]?.[level];
        if (template) {
          templates.push({
            company,
            department,
            level,
            modules: template.modules,
            totalEstimatedMinutes: template.totalEstimatedMinutes,
          });
        }
      }
    }
  }

  return templates;
};

/**
 * Generate a personalized journey with AI enhancements
 * This would integrate with the AI agents to provide intelligent suggestions
 */
export const enhanceJourneyWithAI = async (
  journey: IntelligentOnboardingJourney,
  employeeData: {
    fullName: string;
    email: string;
    position: string;
  }
): Promise<IntelligentOnboardingJourney> => {
  // In a real implementation, this would call the AI agents
  // For now, we'll add AI-generated descriptions to existing modules

  const enhancedModules = journey.modules.map((module) => {
    // Add AI-generated content based on module type
    let aiEnhancedDescription = module.description;

    // In production, this would call appropriate agents:
    // - OnboardingAgent for compliance modules
    // - TrainingAgent for training modules
    // - ITSetupAgent for IT modules
    // etc.

    return {
      ...module,
      description: aiEnhancedDescription,
    };
  });

  return {
    ...journey,
    modules: enhancedModules,
    status: 'generated',
  };
};
