-- Chat Sessions
CREATE TABLE IF NOT EXISTS chat_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    jurisdiction TEXT,
    active_contract_negotiation BOOLEAN DEFAULT FALSE,
    contract_employee_id TEXT,
    contract_collection_state TEXT, -- JSON: {collecting_field: 'field_key', missing_fields: [...]}
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Chat Messages
CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES chat_sessions(id),
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    sources TEXT, -- JSON string or similar
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Employees
CREATE TABLE IF NOT EXISTS employees (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    nric TEXT,
    jurisdiction TEXT NOT NULL,
    position TEXT,
    department TEXT,
    start_date DATE,
    phone TEXT,
    address TEXT,
    bank_name TEXT,
    bank_account TEXT,
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    emergency_contact_relation TEXT,
    status TEXT DEFAULT 'onboarding',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Generated Documents
CREATE TABLE IF NOT EXISTS generated_documents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID NOT NULL REFERENCES employees(id),
    document_type TEXT NOT NULL,
    jurisdiction TEXT NOT NULL,
    employee_name TEXT NOT NULL,
    parameters TEXT, -- JSON string
    file_path TEXT,
    status TEXT DEFAULT 'generated',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Onboarding Documents
CREATE TABLE IF NOT EXISTS onboarding_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID NOT NULL REFERENCES employees(id),
    document_name TEXT NOT NULL,
    required BOOLEAN DEFAULT TRUE,
    submitted BOOLEAN DEFAULT FALSE,
    submitted_at TIMESTAMP WITH TIME ZONE,
    notes TEXT
);

-- HR Requests
CREATE TABLE IF NOT EXISTS hr_requests (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID NOT NULL REFERENCES employees(id),
    request_type TEXT NOT NULL,
    description TEXT,
    data TEXT, -- JSON string
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- Pending Employees (Onboarding Workflow)
CREATE TABLE IF NOT EXISTS pending_employees (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    full_name TEXT NOT NULL,
    nric TEXT,
    passport_no TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    jurisdiction TEXT,
    employment_type TEXT,
    position TEXT,
    department TEXT,
    status TEXT DEFAULT 'pending_onboarding',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    offer_accepted_at TIMESTAMP WITH TIME ZONE,
    documents_generated_at TIMESTAMP WITH TIME ZONE,
    onboarding_completed_at TIMESTAMP WITH TIME ZONE,
    dispute_reason TEXT,
    dispute_details TEXT,
    disputed_at TIMESTAMP WITH TIME ZONE
);

-- Offer Letters
CREATE TABLE IF NOT EXISTS offer_letters (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID NOT NULL REFERENCES pending_employees(id),
    position TEXT,
    department TEXT,
    start_date DATE,
    salary NUMERIC,
    currency TEXT,
    employment_type TEXT,
    probation_months INTEGER,
    reporting_to TEXT,
    work_location TEXT,
    medical_coverage TEXT,
    annual_leave_days INTEGER,
    bonus_details TEXT,
    other_benefits TEXT,
    status TEXT DEFAULT 'sent',
    accepted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- HR Notifications
CREATE TABLE IF NOT EXISTS hr_notifications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    type TEXT,
    nric TEXT,
    passport_no TEXT,
    name TEXT,
    email TEXT,
    phone TEXT,
    message TEXT,
    jurisdiction TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Offer Acceptance Log
CREATE TABLE IF NOT EXISTS offer_acceptance_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID,
    action TEXT,
    ip_address TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Offer Disputes
CREATE TABLE IF NOT EXISTS offer_disputes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID,
    dispute_reason TEXT,
    dispute_details TEXT,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);



-- Pending Documents
CREATE TABLE IF NOT EXISTS pending_documents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID REFERENCES pending_employees(id),
    document_name TEXT,
    file_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);



-- Users (App Profile)
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY REFERENCES auth.users(id),
    email TEXT UNIQUE NOT NULL,
    first_name TEXT,
    last_name TEXT,
    role TEXT CHECK (role IN ('hr_admin', 'employee')),
    department TEXT,
    employee_id TEXT,
    position_title TEXT,
    nationality TEXT,
    start_date DATE,
    onboarding_complete BOOLEAN DEFAULT FALSE,
    nric TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Contracts (Signing Workflow)
CREATE TABLE IF NOT EXISTS contracts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID REFERENCES users(id),
    status TEXT DEFAULT 'draft',
    hr_signed_at TIMESTAMP WITH TIME ZONE,
    hr_user_id UUID REFERENCES users(id),
    employee_signed_at TIMESTAMP WITH TIME ZONE,
    employee_signature_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- HR Employee Assignments
CREATE TABLE IF NOT EXISTS hr_employee_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hr_user_id UUID REFERENCES users(id),
    employee_user_id UUID REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(hr_user_id, employee_user_id)
);

-- Employee Documents (Expiry Tracking)
CREATE TABLE IF NOT EXISTS employee_documents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID NOT NULL REFERENCES employees(id),
    document_type TEXT NOT NULL,           -- 'contract', 'passport', 'visa', 'employment_pass', 'work_permit'
    document_number TEXT,
    issue_date DATE,
    expiry_date DATE NOT NULL,
    status TEXT DEFAULT 'valid',           -- computed: 'valid', 'expiring_30', 'expiring_60', 'expiring_90', 'expired'
    jurisdiction TEXT,
    issuing_authority TEXT,
    notes TEXT,
    renewed_at TIMESTAMP WITH TIME ZONE,
    previous_document_id UUID REFERENCES employee_documents(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_employee_documents_expiry ON employee_documents(expiry_date);
CREATE INDEX IF NOT EXISTS idx_employee_documents_employee ON employee_documents(employee_id);
CREATE INDEX IF NOT EXISTS idx_employee_documents_status ON employee_documents(status);

